name: state_managements_exploration
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ./templates/ui_kit
  riverpod_template:
    path: ./templates/riverpod_template
  mobx_template:
    path: ./templates/mobx_template
  redux_template:
    path: ./templates/redux_template
  bloc_template:
    path: ./templates/bloc_template


  cupertino_icons: ^1.0.2
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true