name: ui_kit
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.4.1
  get_it: ^7.6.0
  dio: ^5.3.2
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  provider: ^6.0.5
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

